apiVersion: v2
name: umap
description: A Helm chart to deploy umap on Kubernetes

type: application

version: 1.0.0

appVersion: "3.0.0"

dependencies:
  - name: cnpg-cluster
    version: 2.0.1
    repository: https://charts.enix.io/
    alias: cnpg
    condition: cnpg.enabled
