apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "umap.fullname" . }}
  labels:
    {{- include "umap.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "umap.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secret-config.yaml") . | sha256sum }}
        checksum/env: {{ .Values.umap.environment | toYaml | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "umap.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "umap.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: asgi
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          startupProbe:
            httpGet:
              path: /stats
              port: asgi
          livenessProbe:
            httpGet:
              path: /stats
              port: asgi
          readinessProbe:
            httpGet:
              path: /stats
              port: asgi
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: UMAP_SETTINGS
            value: /etc/umap/umap.conf
          {{- if .Values.cnpg.enabled }}
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-cnpg-app
                key: uri
          {{- end }}
          {{- with .Values.umap.environment }}
          {{ . | toYaml | nindent 10 }}
          {{- end }}
          {{- if .Values.umap.envFromSecret }}
          envFrom:
          - secretRef:
              name: {{ .Values.umap.envFromSecret }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /etc/umap/
              readOnly: true
            - name: statics
              mountPath: /srv/umap/static
          {{- if .Values.persistence.enabled }}
            - name: data
              mountPath: /srv/umap/uploads/
          {{- end }}
        - name: {{ .Chart.Name }}-nginx
          securityContext:
            {{- toYaml .Values.nginx.securityContext | nindent 12 }}
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
          imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.nginx.service.port }}
              protocol: TCP
          startupProbe:
            httpGet:
              path: /
              port: http
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.nginx.resources | nindent 12 }}
          volumeMounts:
            - name: config-nginx
              mountPath: /etc/nginx/nginx.conf
              readOnly: true
              subPath: nginx.conf
            - name: statics
              mountPath: /static
          {{- if .Values.persistence.enabled }}
            - name: data
              mountPath: /data
          {{- end }}
      volumes:
        - name: config
          secret:
            {{- if .Values.umap.configFromSecret }}
            secretName: {{ .Values.umap.configFromSecret }}
            {{- else }}
            secretName: {{ include "umap.fullname" . }}-config
            {{- end }}
        - name: config-nginx
          configMap:
            name: {{ include "umap.fullname" . }}-nginx-config
        - name: statics
          emptyDir: {}
      {{- if .Values.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "umap.pvcName" . }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
