{{ if not .Values.umap.configFromSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "umap.fullname" . }}-config
  labels:
    {{- include "umap.labels" . | nindent 4 }}
type: Opaque
data:
  umap.conf: {{ .Values.umap.config | b64enc }}
{{- end }}
